# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
            },
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=120, null=True)),
                ('item_brand', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('item_model', models.CharField(blank=True, max_length=120, null=True)),
                ('item_desc', models.TextField(blank=True, max_length=120, null=True)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.ItemCategory', verbose_name='item categories')),
            ],
            options={
                'verbose_name': 'item name',
                'verbose_name_plural': 'item names',
            },
        ),
        migrations.CreateModel(
            name='ItemSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=120, null=True)),
                ('supplier_add', models.TextField(blank=True, null=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item supplier',
                'verbose_name_plural': 'item suppliers',
            },
        ),
        migrations.AddField(
            model_name='itemname',
            name='item_supp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.ItemSupply', verbose_name='item supplier'),
        ),
    ]
