# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190212_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='item_wrty_lngth',
            field=models.IntegerField(default=12, help_text='input by month', verbose_name='item warranty length'),
            preserve_default=False,
        ),
    ]
