# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20190212_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemsupply',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemsupply',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
