# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190213_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.image_upload_location),
        ),
    ]
