# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
