# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customername_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customername',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customername',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
