# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'item RMA',
            },
        ),
        migrations.CreateModel(
            name='ItemWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=60, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerName')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemName')),
            ],
            options={
                'verbose_name_plural': 'item warranties',
            },
        ),
        migrations.AddField(
            model_name='itemrma',
            name='item_warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranties.ItemWarranty'),
        ),
    ]
