# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0002_auto_20190213_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrma',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
