# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0003_itemrma_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemrma',
            name='remarks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warranties.Remarks'),
        ),
    ]
